### ISSUE TITLE
Create Topics and add Ideas

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#1]
## Value proposition
**As a** user 
**I need**  organize Topics to discuss in a Group and add needs to each Topic
**to be able to** get an overview of a topic and find a respective solution

## Description

![Screenshot from 2021-11-23 15-47-16](https://user-images.githubusercontent.com/59687330/143046484-99b5e63f-a3b4-4bf1-a9fb-db87220d33d3.png)

## Acceptance Criteria

- [x] Display of Topic plus description and posted Needs
- [x] Show a Form for adding Topics 
- [x] Show a Form for adding Needs

## Tasks
- [x] create a display for topic title and description
- [x] create a list of needs new ones first
- [x] create a Form Component for a Topic
- [x] create a Form Component for Needs
- [x] create a Button Component with different colors and a variable border
