### ISSUE TITLE
Solution Proposal

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#13]
## Value proposition
**As a** user 
**I need**  to be able to propose a solution to the topic
**to be able to** discuss this with others and keep track of the resistance towards the solution.

## Description

![Screenshot 2021-11-24 at 16-01-34 Excalidraw](https://user-images.githubusercontent.com/59687330/143262325-8120b2ab-c8f0-45d3-b5d9-5fc5e770bbe9.png)

## Acceptance Criteria

- [x] A Solution can be proposed via a Proposal Form to a topic.
- [x] In the Form all needs are displayed as a checklist.
- [x] The user can switch between the needs tab and the proposal tab
- [x] the proposals are listed as cards with three counters for agree, indifferent and "Changes Needed"
- [x] any proposal with one count in 'changes needed' is marked red
- [x] from the rest of the proposals the one with the highest agree rate is marked green.

## Tasks

- [x] adapt the data structure of boards
- [x] create a solutions route
- [x] create solution component
- [x] create a solution form
- [x] update the Topic view to switch between needs and solutions
- [x] implement coloring logic for solution cards
