### ISSUE TITLE
MongoDB Backend

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#27]
## Value proposition
**As a** user 
**I need**  save topics permantly 
**to be able to** work with others together over a long period of time.
## Description

Refactor Data structure into a MongoDB such that the data can be accessed quickly and easily.

## Acceptance Criteria

- [x] All functionality remains
- [x] Topics are displayed correctly
- [x] Needs are listed correctly

## Tasks

- [x]  set up a mongDB Atlas DB
- [x] set up a board collection
- [x] set up a topics collection
- [x] set up a needs collection
- [x] create server api endpoints for db querying 
- [x] create a custom Hook for queriying data from DB
- [x] create a file for initializing connection to db when website is visited
- [x] integrate custom hook in all components where data is needed from the DB
