### ISSUE TITLE
Editable Content

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#41]
## Value proposition
**As a** user 
**I need** edit content in the app
**to be able to** adapt to changes and delete unneeded elements.

## Description

![Screenshot 2021-12-06 at 13-52-37 Excalidraw](https://user-images.githubusercontent.com/59687330/144849378-c33d4fcd-0183-4cd8-8a9a-80944502c875.png)

## Acceptance Criteria

- [x] a menu button is displayed on each element
- [x] onclick a menu with edit and delete options appear
- [x] on delete the item gets deleted from db
- [x] on edit the edit form is displayed

## Tasks

- [x] create a menu component
- [x] create the edit logic
- [x] create the delete logic
- [x] add a delete route to the backend for solutions, topics and needs
