### ISSUE TITLE
Routing Structure

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#6]
## Value Proposition
**As a** user
**I need** multi page system
**to be able to** navigate through the app more easily

## Description
The routing consists of the home route, a dynamic route for topics and an add topic route

## Acceptance Criteria
- [x] on homeroute the dashboard is displayed
- [x] on an individual topic route the topic is displayed or a 404 message if that topic doesnt exist
- [x] on the addTopic route the add Topic page is displayed
## Tasks
- [x] create the routing boilerplate
- [x] create a static homeroute
- [x] create a dynamic topic route
- [x] adapt the detail view of a topic to fit a whole screen
- [x] create a add Topic route
- [x] adapt the add topic form to fit the whole screen
