### ISSUE TITLE
Create User Login

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#69]
## Value proposition
**As a** user 
**I need** have a user account
**to be able to** collaborate with other users.

## Description

![Screenshot 2021-12-14 at 12-34-18 Excalidraw](https://user-images.githubusercontent.com/59687330/145990870-d6a5daff-586c-4289-9677-6c3280969f8a.png)

## Acceptance Criteria

- [x] a login page is displayed
- [x] a user can register a new account
- [x] on login the user page is displayed with a list of boards she subscribed to
- [x] inside a board users can be added

## Tasks

- [x] create login page
- [x] create register page
- [x] create user page
- [x] create add user form
- [x] create user routes in api
