### ISSUE TITLE
Make Needs upvoteable

### ISSUE THREAD

**Issue by F-Kirchhoff** [F-Kirchhoff/capstone-project#9]
## Value proposition
**As a** user 
**I need**  to upvote Needs already in a topic
**to be able to** increase the importance of this need.

## Description

![Screenshot 2021-11-23 at 20-04-08 Excalidraw](https://user-images.githubusercontent.com/59687330/143087696-bfc1cbfd-b555-4e2d-a200-65a5ba884145.png)

## Acceptance Criteria

- [x] display an upvote counter with an upvote and downvote button
- [x] upvote button click increments  the counter 
- [x] downvote button decrements the counter
- [x] list of needs is sorted by upvotes

## Tasks
- [x] create a counter component
- [x] adapt the data structure such that an upvote count  is stored
- [x] set up a state handling in the topic component
- [x] let the counter update function sort the needs array
